# Generated by Django 6.0.6 on 2026-07-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='family_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
