# Generated by Django 6.0.6 on 2026-07-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cart_item_quantity_positive'),
        ),
    ]
