# Generated by Django 6.0.6 on 2026-07-22 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_cart_item_quantity_positive'),
        ('orders', '0002_alter_order_stripe_pi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oversold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='cart.cartitem'),
        ),
    ]
